version: '3.8' #file format version

services:
  app:
    build: .
    container_name: notejam_app
    restart: always
    ports:
      - "5000:4000" 
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: notejam
      DB_PORT: 5432
    volumes:
      - appdata:/app/uploads 
    networks:
      - notejam_network

  db:
    image: postgres:latest
    container_name: notejam_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notejam
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - notejam_network

networks:
  notejam_network:
    name: notejam_network
    # external: true
    
volumes:
  pgdata:
    name: notejam_pgdata 
  appdata:
    name: notejam_appdata
