apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: ayushrai1/notejam-app
          ports:
            - containerPort: 4000
          env:
            - name: DB_CONNECTION
              value: pg
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_HOST
              # value: db
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: postgres
            - name: DB_NAME
              value: notejam
              # not putting the password directly anymore
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password